import type { Service } from "./types";

export const USER_SERVICES: Service[] = [
  {
    id: "u-ageverify",
    name: "Age Verification",
    icon: "\u{1F377}",
    gate: "pop",
    price: "0.10",
    ctx: "Alcohol delivery, restricted purchases",
    desc: "Proves you're of legal age for restricted purchases \u2014 alcohol delivery, tobacco, age-gated content. Your agent handles age-checks on every order without you pulling out your ID each time.",
    scenario: "Your agent orders a bottle of wine from an online retailer. The retailer's API requires age verification. FaceSign liveness proves you're a real adult human \u2014 done once, reused on every future order from any retailer.",
  },
  {
    id: "u-creditpull",
    name: "Credit Report Pull",
    icon: "\u{1F4CA}",
    gate: "kyc",
    price: "3.50",
    ctx: "Mortgage rate-shopping, loan applications",
    desc: "Soft credit pull from a credit bureau. Your agent rate-shops your mortgage across lenders, pulling your score from each \u2014 without you re-verifying your identity every time.",
    scenario: "You tell your agent to find the best mortgage rate. It needs to pull your credit from multiple bureaus across multiple lenders. Today that's 5+ separate identity verifications. With Trusted Agents: verify once, your agent pulls from all of them.",
  },
  {
    id: "u-bgcheck",
    name: "Background Check",
    icon: "\u{1F50D}",
    gate: "kyc",
    price: "35.00",
    ctx: "Job applications, gig platforms",
    desc: "Employment background check \u2014 criminal records, employment history, education verification. Your agent submits to multiple employers simultaneously, each triggering a check.",
    scenario: "You're job hunting. Your agent submits applications to 20 companies. Each runs a background check. Today: 20 separate identity + consent flows. With Trusted Agents: one KYC credential, your agent consents and verifies instantly for all 20.",
  },
  {
    id: "u-income",
    name: "Income Verification",
    icon: "\u{1F4B0}",
    gate: "kyc",
    price: "25.00",
    ctx: "Apartment applications, loan pre-approval",
    desc: "Verified proof of employment and income for landlords and lenders. Your agent applies to apartments and proves your income to each landlord without you uploading pay stubs every time.",
    scenario: "Apartment hunting. 8 applications to different landlords, each needs proof of income. Your agent handles all 8 \u2014 the KYC credential from your background check already satisfies the identity requirement. Zero additional verification.",
  },
  {
    id: "u-docfiling",
    name: "Regulated Document Filing",
    icon: "\u{1F4DD}",
    gate: "kyc-ag",
    price: "5.00",
    ctx: "Tax returns, corporate filings, legal submissions",
    desc: "File regulated documents where the receiving authority may need to re-verify your identity later. This requires a KYC credential with an access grant so the authority can re-check.",
    scenario: "Your agent files your annual tax return. The tax authority requires KYC with re-verification rights (AG) in case of audit. Your existing KYC credential is reused, but a scoped AG is created giving the authority time-limited read access to your credential hash.",
  },
];

export const DEV_SERVICES: Service[] = [
  {
    id: "d-agegate",
    name: "Age Gate Middleware",
    icon: "\u{1F510}",
    gate: "pop",
    price: "0.10",
    ctx: "E-commerce, delivery platforms, content gates",
    desc: "Add age verification to your platform. Your backend agent calls this API to verify each customer's age before processing restricted orders. Customers verify once via idOS \u2014 your platform never stores their age data.",
    scenario: "You're building a wine delivery app. Regulations require age verification on every order. Instead of each customer uploading IDs to YOUR platform (liability), they verify once through idOS and your agent checks the credential hash per order.",
  },
  {
    id: "d-creditapi",
    name: "Credit Bureau Integration",
    icon: "\u{1F4CA}",
    gate: "kyc",
    price: "3.50",
    ctx: "Lending platforms, mortgage comparison, fintech",
    desc: "Pull credit reports on behalf of your users. Your platform's agent fleet calls bureau APIs for each user \u2014 the user's idOS credential satisfies the bureau's identity requirement without your platform handling PII.",
    scenario: "You're building a mortgage comparison engine. Your agent pulls credit from 3 bureaus for each user. The user verifies once through your app's idOS integration \u2014 your backend agents use their credential across all bureau APIs. You never store their SSN or ID documents.",
  },
  {
    id: "d-screening",
    name: "Tenant Screening Pipeline",
    icon: "\u{1F3E0}",
    gate: "kyc",
    price: "45.00",
    ctx: "Property management, rental platforms",
    desc: "Run comprehensive tenant screening \u2014 credit, background, eviction history, income \u2014 as a single pipeline. Your platform's agent orchestrates multiple API calls per applicant using their portable idOS credential.",
    scenario: "Your property management platform processes 200 applications/month. Each needs credit + background + income checks. Instead of collecting PII from every applicant, they verify once through idOS. Your agent fleet runs all three checks per applicant using the same credential.",
  },
  {
    id: "d-kybcheck",
    name: "Business Verification (KYB)",
    icon: "\u{1F3E2}",
    gate: "kyc-ag",
    price: "15.00",
    ctx: "B2B platforms, procurement, supplier onboarding",
    desc: "Verify business entities and their authorized representatives for B2B platforms. Requires KYC with AG because the platform may need to re-verify the business representative's authority periodically.",
    scenario: "Your procurement platform onboards new suppliers. Each supplier's authorized representative verifies their identity and business authority through idOS. Your platform gets an AG for periodic re-verification \u2014 required by your compliance team \u2014 without storing supplier PII.",
  },
  {
    id: "d-esign",
    name: "Regulated e-Signature API",
    icon: "\u270D\uFE0F",
    gate: "kyc-ag",
    price: "2.50",
    ctx: "Legal tech, notarization, contract platforms",
    desc: "Identity-verified electronic signatures for regulated documents. The signing counterparty gets a time-limited AG for dispute resolution. Your platform's agents orchestrate multi-party signing flows.",
    scenario: "Your legal tech platform handles contract execution. Each signer verifies via idOS. The counterparty gets a scoped AG so signatures can be verified in disputes. Your platform never holds signer PII \u2014 idOS handles identity, x402 handles payment, your platform handles workflow.",
  },
];
