import type { Service } from "./types";

export const DEFAULT_SERVICES: Service[] = [
  {
    id: "pop-captcha",
    name: "Human Verification Gateway",
    icon: "\u{1F464}",
    desc: "Anti-Sybil check for dApps. Proves a unique human is behind the request \u2014 no bots, no duplicates.",
    gate: "pop",
    price: "0.01",
    color: "green",
    category: "Identity",
  },
  {
    id: "pop-ai",
    name: "AI Inference Endpoint",
    icon: "\u{1F9E0}",
    desc: "Rate-limited LLM inference API. PoP prevents bot abuse while keeping access open to verified humans.",
    gate: "pop",
    price: "0.08",
    color: "purple",
    category: "AI / ML",
  },
  {
    id: "kyc-compliance",
    name: "Compliance Report API",
    icon: "\u{1F50D}",
    desc: "On-chain risk scoring and compliance checks on wallet addresses. Sanctions, PEP screening, jurisdiction analysis.",
    gate: "kyc",
    price: "0.50",
    color: "blue",
    category: "Compliance",
  },
  {
    id: "kyc-credit",
    name: "DeFi Credit Score",
    icon: "\u{1F4CA}",
    desc: "On-chain credit scoring for DeFi lending protocols. Combines repayment history, collateral ratios, and protocol diversity.",
    gate: "kyc",
    price: "2.00",
    color: "blue",
    category: "Finance",
  },
  {
    id: "uniq-airdrop",
    name: "Sybil-Resistant Airdrop",
    icon: "\u{1F3AF}",
    desc: "Token distribution that enforces one claim per verified human. Uniqueness check via idOS.",
    gate: "uniq",
    price: "0.00",
    color: "yellow",
    category: "Distribution",
  },
  {
    id: "kyc-fiat",
    name: "Fiat On/Off-Ramp",
    icon: "\u{1F4B1}",
    desc: "Stablecoin-to-fiat conversion with regulatory compliance. Requires KYC with AG for re-verification by the provider.",
    gate: "kyc-ag",
    price: "0.25",
    color: "orange",
    category: "Payments",
  },
];
