import type { Service } from "./types";

export const USER_SERVICES: Service[] = [
  {
    id: "u-ageverify",
    name: "Age Verification",
    icon: "\u{1F377}",
    gate: "pop",
    price: "0.10",
    ctx: "Alcohol delivery, restricted purchases",
    desc: "Proves you're of legal age for restricted purchases \u2014 alcohol delivery, tobacco, age-gated content. Your agent handles age-checks on every order without you pulling out your ID each time.",
    scenario: "Your agent orders a bottle of wine from an online retailer. The retailer's API requires age verification. FaceSign liveness proves you're a real adult human \u2014 done once, reused on every future order from any retailer.",
  },
  {
    id: "u-creditpull",
    name: "Credit Report Pull",
    icon: "\u{1F4CA}",
    gate: "kyc",
    price: "3.50",
    ctx: "Mortgage rate-shopping, loan applications",
    desc: "Soft credit pull from a credit bureau. Your agent rate-shops your mortgage across lenders, pulling your score from each \u2014 without you re-verifying your identity every time.",
    scenario: "You tell your agent to find the best mortgage rate. It needs to pull your credit from multiple bureaus across multiple lenders. Today that's 5+ separate identity verifications. With Trusted Agents: verify once, your agent pulls from all of them.",
  },
  {
    id: "u-bgcheck",
    name: "Background Check",
    icon: "\u{1F50D}",
    gate: "kyc",
    price: "35.00",
    ctx: "Job applications, gig platforms",
    desc: "Employment background check \u2014 criminal records, employment history, education verification. Your agent submits to multiple employers simultaneously, each triggering a check.",
    scenario: "You're job hunting. Your agent submits applications to 20 companies. Each runs a background check. Today: 20 separate identity + consent flows. With Trusted Agents: one KYC credential, your agent consents and verifies instantly for all 20.",
  },
  {
    id: "u-income",
    name: "Income Verification",
    icon: "\u{1F4B0}",
    gate: "kyc",
    price: "25.00",
    ctx: "Apartment applications, loan pre-approval",
    desc: "Verified proof of employment and income for landlords and lenders. Your agent applies to apartments and proves your income to each landlord without you uploading pay stubs every time.",
    scenario: "Apartment hunting. 8 applications to different landlords, each needs proof of income. Your agent handles all 8 \u2014 the KYC credential from your background check already satisfies the identity requirement. Zero additional verification.",
  },
  {
    id: "u-docfiling",
    name: "Regulated Document Filing",
    icon: "\u{1F4DD}",
    gate: "kyc-ag",
    price: "5.00",
    ctx: "Tax returns, corporate filings, legal submissions",
    desc: "File regulated documents where the receiving authority may need to re-verify your identity later. This requires a KYC credential with an access grant so the authority can re-check.",
    scenario: "Your agent files your annual tax return. The tax authority requires KYC with re-verification rights (AG) in case of audit. Your existing KYC credential is reused, but a scoped AG is created giving the authority time-limited read access to your credential hash.",
  },
];

export const APP_SERVICES: Service[] = [
  {
    id: "d-agegate",
    name: "Age Gate Middleware",
    icon: "\u{1F510}",
    gate: "pop",
    price: "0.10",
    ctx: "E-commerce, delivery platforms, content gates",
    desc: "Add age verification to your platform. Your backend agent calls this API to verify each customer's age before processing restricted orders. Customers verify once via idOS \u2014 your platform never stores their age data.",
    scenario: "You're building a wine delivery app. Regulations require age verification on every order. Instead of each customer uploading IDs to YOUR platform (liability), they verify once through idOS and your agent checks the credential hash per order.",
  },
  {
    id: "d-creditapi",
    name: "Credit Bureau Integration",
    icon: "\u{1F4CA}",
    gate: "kyc",
    price: "3.50",
    ctx: "Lending platforms, mortgage comparison, fintech",
    desc: "Pull credit reports on behalf of your users. Your platform's agent fleet calls bureau APIs for each user \u2014 the user's idOS credential satisfies the bureau's identity requirement without your platform handling PII.",
    scenario: "You're building a mortgage comparison engine. Your agent pulls credit from 3 bureaus for each user. The user verifies once through your app's idOS integration \u2014 your backend agents use their credential across all bureau APIs. You never store their SSN or ID documents.",
  },
  {
    id: "d-screening",
    name: "Tenant Screening Pipeline",
    icon: "\u{1F3E0}",
    gate: "kyc",
    price: "45.00",
    ctx: "Property management, rental platforms",
    desc: "Run comprehensive tenant screening \u2014 credit, background, eviction history, income \u2014 as a single pipeline. Your platform's agent orchestrates multiple API calls per applicant using their portable idOS credential.",
    scenario: "Your property management platform processes 200 applications/month. Each needs credit + background + income checks. Instead of collecting PII from every applicant, they verify once through idOS. Your agent fleet runs all three checks per applicant using the same credential.",
  },
  {
    id: "d-kybcheck",
    name: "Business Verification (KYB)",
    icon: "\u{1F3E2}",
    gate: "kyc-ag",
    price: "15.00",
    ctx: "B2B platforms, procurement, supplier onboarding",
    desc: "Verify business entities and their authorized representatives for B2B platforms. Requires KYC with AG because the platform may need to re-verify the business representative's authority periodically.",
    scenario: "Your procurement platform onboards new suppliers. Each supplier's authorized representative verifies their identity and business authority through idOS. Your platform gets an AG for periodic re-verification \u2014 required by your compliance team \u2014 without storing supplier PII.",
  },
  {
    id: "d-esign",
    name: "Regulated e-Signature API",
    icon: "\u270D\uFE0F",
    gate: "kyc-ag",
    price: "2.50",
    ctx: "Legal tech, notarization, contract platforms",
    desc: "Identity-verified electronic signatures for regulated documents. The signing counterparty gets a time-limited AG for dispute resolution. Your platform's agents orchestrate multi-party signing flows.",
    scenario: "Your legal tech platform handles contract execution. Each signer verifies via idOS. The counterparty gets a scoped AG so signatures can be verified in disputes. Your platform never holds signer PII \u2014 idOS handles identity, x402 handles payment, your platform handles workflow.",
  },
];

export const DEV_AGENT_SERVICES: Service[] = [
  // ── Infrastructure ──
  {
    id: "da-cloud",
    name: "Cloud Provisioning",
    icon: "☁️",
    gate: "kyc",
    price: "2.00",
    ctx: "AWS, GCP, Azure programmatic setup",
    desc: "Provision cloud infrastructure programmatically. Your coding agent spins up environments, configures VPCs, and manages resources — the cloud provider verifies your identity once via idOS.",
    scenario: "Your AI coding agent needs to create a staging environment on AWS. Instead of manually logging in, the agent provisions resources using your KYC credential for identity verification.",
  },
  {
    id: "da-dns",
    name: "DNS Management",
    icon: "🌐",
    gate: "kyc",
    price: "0.50",
    ctx: "Domain registration, DNS record updates",
    desc: "Register domains and manage DNS records. Your agent handles DNS changes across providers — verified identity prevents unauthorized domain hijacking.",
    scenario: "Your coding agent needs to configure DNS for a new microservice. It registers the subdomain and sets up records, verified through your idOS credential.",
  },
  {
    id: "da-ssl",
    name: "SSL/TLS Certificates",
    icon: "🔒",
    gate: "kyc",
    price: "1.00",
    ctx: "Certificate issuance, renewal, revocation",
    desc: "Issue and manage SSL/TLS certificates. Identity verification ensures only authorized developers can provision certs for their domains.",
    scenario: "Your agent auto-renews expiring SSL certificates across your services. The CA verifies your identity through idOS — no manual certificate management.",
  },
  {
    id: "da-registry",
    name: "Container Registry",
    icon: "📦",
    gate: "pop",
    price: "0.25",
    ctx: "Docker images, OCI artifacts, private registries",
    desc: "Push and pull container images from private registries. PoP verification prevents unauthorized image pushes to your org's registry.",
    scenario: "Your coding agent builds a Docker image and pushes it to your private registry. PoP verification ensures only authenticated humans authorize image publications.",
  },
  // ── Code & Build ──
  {
    id: "da-codesign",
    name: "Code Signing",
    icon: "✍️",
    gate: "kyc-ag",
    price: "1.50",
    ctx: "Binary signing, release verification, supply chain",
    desc: "Sign binaries and release artifacts. KYC with AG ensures signing authority can be re-verified — critical for supply chain integrity.",
    scenario: "Your agent builds a release binary and signs it. The signing certificate is tied to your KYC credential with an AG so downstream consumers can verify the signer's identity.",
  },
  {
    id: "da-publish",
    name: "Package Publishing",
    icon: "📤",
    gate: "kyc",
    price: "0.75",
    ctx: "npm, PyPI, crates.io, package registries",
    desc: "Publish packages to public registries. Identity-gated publishing prevents supply chain attacks from compromised CI/CD.",
    scenario: "Your coding agent publishes a new npm package version. The registry verifies your identity through idOS — no stored API tokens that could be leaked.",
  },
  {
    id: "da-cicd",
    name: "CI/CD Pipeline Auth",
    icon: "⚙️",
    gate: "pop",
    price: "0.10",
    ctx: "GitHub Actions, GitLab CI, build pipelines",
    desc: "Authenticate to CI/CD systems and trigger builds. PoP verification ensures a real human authorized the pipeline run.",
    scenario: "Your agent triggers a production deployment pipeline. PoP verification confirms a real developer authorized it — preventing rogue automated deployments.",
  },
  {
    id: "da-audit",
    name: "Code Security Audit",
    icon: "🔬",
    gate: "kyc",
    price: "15.00",
    ctx: "SAST, DAST, dependency scanning, code review",
    desc: "Run comprehensive security audits on your codebase. Identity verification ensures audit results are tied to an accountable developer.",
    scenario: "Your agent submits your codebase for a security audit. The audit service verifies your identity — results and vulnerability reports are tied to your verified account.",
  },
  // ── Security & Compliance ──
  {
    id: "da-pentest",
    name: "Pentest Authorization",
    icon: "🛡️",
    gate: "kyc-ag",
    price: "50.00",
    ctx: "Penetration testing, bug bounty, security scanning",
    desc: "Authorize automated penetration testing. KYC+AG ensures the tester's identity is verifiable and re-checkable for legal accountability.",
    scenario: "Your agent launches an automated pentest against your staging environment. The pentest service requires KYC+AG so your authorization can be legally verified.",
  },
  {
    id: "da-soc2",
    name: "SOC2 Evidence Collection",
    icon: "📋",
    gate: "kyc-ag",
    price: "25.00",
    ctx: "Compliance evidence, audit trails, SOC2/ISO",
    desc: "Collect and submit SOC2 compliance evidence. AG ensures auditors can re-verify the submitter's identity during the audit window.",
    scenario: "Your agent gathers SOC2 evidence — access logs, config snapshots, policy docs — and submits them. The compliance platform verifies your identity with AG for auditor re-verification.",
  },
  {
    id: "da-vulnscan",
    name: "Vulnerability Scanning",
    icon: "🔍",
    gate: "kyc",
    price: "5.00",
    ctx: "CVE scanning, dependency audit, SBOM generation",
    desc: "Scan infrastructure and dependencies for vulnerabilities. Identity verification ties scan results to an accountable owner.",
    scenario: "Your coding agent runs a full vulnerability scan across your production infrastructure. Results are tied to your verified identity for compliance reporting.",
  },
  {
    id: "da-secrets",
    name: "Secret Management",
    icon: "🔑",
    gate: "kyc",
    price: "0.50",
    ctx: "Vault, KMS, secret rotation, key management",
    desc: "Manage secrets and encryption keys. Identity-gated access ensures only verified developers can rotate or access production secrets.",
    scenario: "Your agent rotates database credentials and API keys across environments. The secrets manager verifies your identity — no shared service accounts.",
  },
  // ── Data & Services ──
  {
    id: "da-dbprov",
    name: "Database Provisioning",
    icon: "🗄️",
    gate: "kyc",
    price: "3.00",
    ctx: "Postgres, Redis, managed databases",
    desc: "Provision and configure managed databases. Identity verification prevents unauthorized database creation in your cloud accounts.",
    scenario: "Your agent provisions a new Postgres instance for a feature branch. The cloud provider verifies your identity through idOS — isolated environments without manual setup.",
  },
  {
    id: "da-payments",
    name: "Payment Sandbox",
    icon: "💳",
    gate: "kyc",
    price: "1.00",
    ctx: "Stripe test mode, payment processor sandboxes",
    desc: "Access payment processor sandbox environments. Identity verification ensures only authorized developers can create test accounts and process test payments.",
    scenario: "Your agent sets up a Stripe sandbox for integration testing. KYC verification ensures your test environment is tied to a verified developer account.",
  },
  {
    id: "da-email",
    name: "Email Service Setup",
    icon: "📧",
    gate: "pop",
    price: "0.25",
    ctx: "SendGrid, Postmark, transactional email",
    desc: "Configure transactional email services. PoP verification prevents bot abuse of email-sending APIs.",
    scenario: "Your coding agent configures SendGrid for your app's transactional emails. PoP verification prevents automated mass email abuse.",
  },
  {
    id: "da-monitor",
    name: "Monitoring Setup",
    icon: "📊",
    gate: "pop",
    price: "0.50",
    ctx: "Datadog, Grafana, alerting, observability",
    desc: "Set up monitoring and alerting for your services. PoP ensures a real human authorized the observability configuration.",
    scenario: "Your agent sets up Datadog monitoring with custom dashboards and alerts. PoP verification ensures a real developer authorized the configuration.",
  },
  // ── Legal & Regulatory ──
  {
    id: "da-tos",
    name: "ToS Acceptance",
    icon: "📜",
    gate: "kyc-ag",
    price: "0.10",
    ctx: "Terms of Service, EULA, legal agreements",
    desc: "Accept Terms of Service on behalf of your organization. KYC+AG ensures the acceptor's identity is verifiable for legal enforceability.",
    scenario: "Your agent accepts a cloud provider's updated ToS. KYC+AG verification ensures the acceptance is legally binding and the signer's identity is re-verifiable.",
  },
  {
    id: "da-dpa",
    name: "DPA Signing",
    icon: "🤝",
    gate: "kyc-ag",
    price: "2.00",
    ctx: "Data Processing Agreements, GDPR, privacy",
    desc: "Sign Data Processing Agreements with service providers. Identity verification with AG ensures both parties can re-verify signers for GDPR compliance.",
    scenario: "Your agent signs a DPA with a new SaaS vendor. The vendor requires KYC+AG so they can re-verify the authorized signer during data protection audits.",
  },
  {
    id: "da-export",
    name: "Export Compliance",
    icon: "🌍",
    gate: "kyc",
    price: "5.00",
    ctx: "Export controls, sanctions screening, ITAR/EAR",
    desc: "Screen against export control lists before deploying to international regions. Identity verification ensures the deployer is screened against sanctions lists.",
    scenario: "Your agent deploys to a new geographic region. The compliance service screens your identity against export control lists before allowing the deployment.",
  },
  {
    id: "da-license",
    name: "License Procurement",
    icon: "📄",
    gate: "kyc",
    price: "10.00",
    ctx: "Software licenses, enterprise seats, API keys",
    desc: "Procure software licenses and API keys. Identity verification ensures licenses are tied to verified organizational accounts.",
    scenario: "Your agent procures enterprise seats for a new dev tool. The vendor verifies your identity through idOS — no manual procurement workflows.",
  },
];
